### ISSUE TITLE
`require('arachne').rename()` dont work

### ISSUE THREAD

**Issue by steinbrueckri** [oem/arachne.nvim#1] opened 2022-10-05 09:41 UTC
```
E5108: Error executing lua ...site/pack/packer/start/arachne.nvim/lua/arachne/init.lua:42: attempt to concatenate local 'title' (a nil value)
stack traceback:
        ...site/pack/packer/start/arachne.nvim/lua/arachne/init.lua:42: in function 'rename'
        [string ":lua"]:1: in main chunk
```

<img width="2560" alt="Bildschirmfoto 2022-10-05 um 11 38 59" src="https://user-images.githubusercontent.com/578303/194030884-a438f2b7-3600-4b70-ba67-babb70fd8de7.png">

```
$ nvim -v                                                                                                                                                                                       3.8m
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Übersetzt von brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

          System-vimrc-Datei: "$VIM/sysinit.vim"
     Voreinstellung für $VIM: "/opt/homebrew/Cellar/neovim/0.8.0/share/nvim"

Run :checkhealth for more info
```

**Comment by oem** [comment] 2022-10-06 08:48
Heya - thanks for reporting the issue: It should now be fixed with the newest version. I will close the issue but feel free to comment on tis or open a new issue if you still encounter problems
The cause for this was that the original file to be renamed did not follow the naming scheme of the arachne notes, one can now rename any file to a note conforming to the naming scheme.

**Closed as completed by oem** 2022-10-06 08:48 UTC

**Comment by steinbrueckri** [comment] 2022-10-06 08:58
@oem Thx for the fast fix, works as you expect it.
